// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using son;

#nullable disable

namespace son.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240522214126_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("son.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Blok")
                        .HasColumnType("text");

                    b.Property<string>("Nitelik")
                        .HasColumnType("text");

                    b.Property<int?>("fKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blok = "b1",
                            Nitelik = "n1",
                            fKey = 1
                        },
                        new
                        {
                            Id = 2,
                            Blok = "b2",
                            Nitelik = "n2",
                            fKey = 2
                        });
                });

            modelBuilder.Entity("son.Models.Parcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ada")
                        .HasColumnType("integer");

                    b.Property<string>("Pafta")
                        .HasColumnType("text");

                    b.Property<int?>("ParselNo")
                        .HasColumnType("integer");

                    b.Property<string>("il")
                        .HasColumnType("text");

                    b.Property<string>("ilce")
                        .HasColumnType("text");

                    b.Property<string>("mahalle")
                        .HasColumnType("text");

                    b.Property<string>("nitelik")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ada = 1,
                            Pafta = "P1",
                            ParselNo = 101,
                            il = "Ankara",
                            ilce = "Çankaya",
                            mahalle = "Kızılay",
                            nitelik = "Residential"
                        },
                        new
                        {
                            Id = 2,
                            Ada = 2,
                            Pafta = "P2",
                            ParselNo = 102,
                            il = "Ankara",
                            ilce = "Çankaya",
                            mahalle = "Bahçelievler",
                            nitelik = "Commercial"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
